
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class MyCalendar extends javax.swing.JFrame {

    protected static String year[] = years();
    private int n;
    private Employee emp;
    public MyCalendar(int n, Employee emp) {
        this.emp = emp;
        this.n = n;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        ShowDate();
        ShowTime();
        dateNot.setVisible(false);
    }
    void ShowDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("EEEE dd-MM-yyyy");
        date1.setText(s.format(d)); 
    }
    void ShowTime(){
        new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
              Date d = new Date();
              SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
              time1.setText(s.format(d));
               
            }
               
        }
        ).start();
    }
    public static String[] years(){
      String years[] = new String[100];
      int year = Calendar.getInstance().get(Calendar.YEAR);
      for (int i = 1; i < years.length; i++) {
        years[i]= String.valueOf(year);
        year++;        	
      }
      return years;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        today = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        showCale = new javax.swing.JLabel();
        select = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        days = new javax.swing.JComboBox();
        slash1 = new javax.swing.JLabel();
        month = new javax.swing.JComboBox();
        slash2 = new javax.swing.JLabel();
        years = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        dateNot = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        taskAndRem = new javax.swing.JLabel();	
        jScrollPane1 = new javax.swing.JScrollPane();	
        jList1 = new javax.swing.JList();	
        jLabel3 = new javax.swing.JLabel();	
        jScrollPane2 = new javax.swing.JScrollPane();	
        eventsList2 = new javax.swing.JList();	
        	
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 222, 89));
        setIconImage(Toolkit.getDefaultToolkit().getImage(MyCalendar.class.getResource("/images/smallLogo.PNG")));

        jPanel1.setBackground(new java.awt.Color(255, 222, 89));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/busyb.jpg"))); // NOI18N

        today.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        today.setText("Today");

        time1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        time1.setText("Time");

        date1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        date1.setText("Date");

        showCale.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        showCale.setText("Show Calendar");

        select.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        select.setText("Select date:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("here");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("If you want to add Task, Event or Reminder to your Program press");

        days.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        slash1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        slash1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slash1.setText("/");

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        slash2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        slash2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slash2.setText("/");

        years.setModel(new javax.swing.DefaultComboBoxModel(year));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jLabel13.setText("Home");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        OKButton.setText("OK");
        OKButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKButtonMouseClicked(evt);
            }
        });

        dateNot.setForeground(new java.awt.Color(255, 0, 0));
        dateNot.setText("Not valid date. Please try again!");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Sort by:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "Title", "Level of importance" }));
        jComboBox1.setSelectedIndex(1);
        taskAndRem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N	
        taskAndRem.setText("Tasks and Reminders");	
        jList1.setModel(model1);
        jScrollPane1.setViewportView(jList1);	
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N	
        jLabel3.setText("Events");	
        eventsList2.setModel(model2);	
        jScrollPane2.setViewportView(eventsList2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(time1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(today, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)	
                            .addGroup(jPanel1Layout.createSequentialGroup()	
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)	
                                    .addComponent(showCale)	
                                    .addGroup(jPanel1Layout.createSequentialGroup()	
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)	
                                            .addGroup(jPanel1Layout.createSequentialGroup()	
                                                .addComponent(select)	
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))	
                                            .addGroup(jPanel1Layout.createSequentialGroup()	
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)	
                                                .addGap(27, 27, 27)))	
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)	
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)	
                                            .addGroup(jPanel1Layout.createSequentialGroup()	
                                                .addComponent(days, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)	
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)	
                                                .addComponent(slash1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)	
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)	
                                                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)	
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)	
                                                .addComponent(slash2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)	
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)	
                                                .addComponent(years, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))	
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()	
                                        .addGap(10, 10, 10)	
                                        .addComponent(taskAndRem)))	
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)	
                                    .addGroup(jPanel1Layout.createSequentialGroup()	
                                        .addGap(628, 628, 628)	
                                        .addComponent(jLabel13))	
                                    .addGroup(jPanel1Layout.createSequentialGroup()	
                                        .addGap(18, 18, 18)	
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)	
                                            .addComponent(dateNot)	
                                            .addGroup(jPanel1Layout.createSequentialGroup()	
                                                .addGap(48, 48, 48)	
                                                .addComponent(OKButton))))))	
                            .addGroup(jPanel1Layout.createSequentialGroup()	
                                .addGap(10, 10, 10)	
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)	
                                    .addComponent(jLabel3)	
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)	
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))))))	
                .addContainerGap())
            );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(today)
                            .addComponent(showCale)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(days, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(select)
                            .addComponent(slash1)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slash2)
                            .addComponent(years, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OKButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(time1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateNot, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)	
                .addComponent(taskAndRem)	
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)	
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)	
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)	
                .addComponent(jLabel3)	
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)	
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)	
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        new FirstWindow(emp).setVisible(true);        
        this.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new TaskOrReminderWindow1(n, emp).setVisible(true);        
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked
    
    private void OKButtonMouseClicked(java.awt.event.MouseEvent evt) { 
        String date1;
        if (days.getSelectedItem() == null || month.getSelectedItem() == null 
                || years.getSelectedItem() == null)
            dateNot.setVisible(true);
        else 
            dateNot.setVisible(false);
            date1 = days.getSelectedItem().toString() + "/" + 
                        month.getSelectedItem().toString() + "/" +
                        years.getSelectedItem().toString();
            if (!Day.validDate(date1))
                dateNot.setVisible(true);
            else
                model1.removeAllElements();
                model2.removeAllElements();
                dateNot.setVisible(false);
                ArrayList<Task> tasks = new ArrayList<Task>();
                tasks = Task.onlyTasksList(emp.searchDay(date1).getDailyProgram());               
                if (tasks.isEmpty()){
                    model1.addElement("No Tasks or Reminders for today");
                } else {
                    int i;
                    if(String.valueOf(jComboBox1.getSelectedItem()).equals("Date")){
                        tasks = Task.sortByDate(tasks);
                    } else if (String.valueOf(jComboBox1.getSelectedItem()).equals("Description")){
                        tasks = Task.sortByDesc(tasks);
                    } else {
                        tasks = Task.sortByImp(tasks);
                    }
                    for (i = 0; i < tasks.size(); i++){
                        model1.addElement(tasks.get(i));
                    }
                }
                jList1.setModel(model1);
                ArrayList<String> eventsList = Event.onlyEventsList(emp.searchDay(date1).getDailyProgram());
                if (!eventsList.isEmpty()){
                    for (int i = 0; i < eventsList.size(); i++){
                        model2.addElement(eventsList.get(i));
                    }
                } else 
                    model2.addElement("No events for today");    

    }       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCalendar(4).setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel dateNot;
    private javax.swing.JComboBox days;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDPro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox month;
    private javax.swing.JLabel select;
    private javax.swing.JLabel showCale;
    private javax.swing.JLabel slash1;
    private javax.swing.JLabel slash2;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel today;
    private javax.swing.JComboBox years;
    private javax.swing.JLabel taskAndRem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jList1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList eventsList2;
    DefaultListModel model1 = new DefaultListModel();
    DefaultListModel model2 = new DefaultListModel();
               
    // End of variables declaration//GEN-END:variables
}
